export interface SyllabusSession {
  session: number
  topic: string
  isTest?: boolean
}

export type SyllabusLevel =
  | 'Beginner'
  | 'Foundation 1' | 'Foundation 2' | 'Foundation 3' | 'Foundation 4'
  | 'Intermediate 1' | 'Intermediate 2' | 'Intermediate 3' | 'Intermediate 4'

export const SYLLABUS: Record<SyllabusLevel, SyllabusSession[]> = {
  'Beginner': [
    { session: 1,  topic: 'Chessboard, pieces, setup & goal of the game (Checkmate). Understanding the Rook.' },
    { session: 2,  topic: 'Understanding the Bishop, Queen, and Pawn. Game Notation.' },
    { session: 3,  topic: 'Understanding the King, Knight, and value of all the pieces.' },
    { session: 4,  topic: 'Attack, capture, and capturing hanging pieces.' },
    { session: 5,  topic: 'Four ways of protection (ABCD).' },
    { session: 6,  topic: 'Giving checks, 3 methods of defence against checks, introduction to checkmate.' },
    { session: 7,  topic: 'Test on capturing hanging pieces with all the pieces – mixed exercises.' },
    { session: 8,  topic: 'Test 1', isTest: true },
    { session: 9,  topic: 'Exercises on giving checks and getting out of check & ABCD of defence.' },
    { session: 10, topic: 'Checkmate in one move – major and minor pieces. Center squares, extended center, camps.' },
    { session: 11, topic: 'Castling.' },
    { session: 12, topic: 'En passant and pawn promotion.' },
    { session: 13, topic: 'Assisted checkmates in one move – Queen, Rook, Bishop, Knight, and Pawn.' },
    { session: 14, topic: 'Choosing the correct captures – legal captures and capturing only hanging pieces.' },
    { session: 15, topic: 'Choosing the right capture (Part 2) – value of pieces, profitable exchanges.' },
    { session: 16, topic: 'Test 2', isTest: true },
    { session: 17, topic: 'Direct and assisted checkmate exercises – mixed.' },
    { session: 18, topic: 'Types of draws – stalemate and the rules of draws.' },
    { session: 19, topic: 'Other rules of draws – agreement, threefold repetition, insufficient material, fifty-move rule.' },
    { session: 20, topic: 'Mixed exercises on special moves and draws in chess.' },
    { session: 21, topic: "Opening checkmates – Fool's Mate, assisted checkmates, 4-move checkmate (and defence)." },
    { session: 22, topic: 'Opening principles – control the center, develop pieces on active squares, and castle.' },
    { session: 23, topic: 'Checkmating with two rooks and the Queen.' },
    { session: 24, topic: 'Final assessment', isTest: true },
  ],

  'Foundation 1': [
    { session: 1,  topic: 'Revision of Beginner topics (Castling, Mate in 1, Opening principles).' },
    { session: 2,  topic: '1 Queen & 2 Rooks Checkmate revision.' },
    { session: 3,  topic: 'Pin.' },
    { session: 4,  topic: 'Skewer.' },
    { session: 5,  topic: 'Double attack.' },
    { session: 6,  topic: 'Knight fork.' },
    { session: 7,  topic: 'Discovered Check and Double check.' },
    { session: 8,  topic: 'Test 1', isTest: true },
    { session: 9,  topic: 'Mate in 1 mix.' },
    { session: 10, topic: 'Opening traps.' },
    { session: 11, topic: 'Defend against Mate.' },
    { session: 12, topic: 'Punishing bad opening moves.' },
    { session: 13, topic: 'Back-Rank Mate.' },
    { session: 14, topic: 'Simple checkmate in 2 moves.' },
    { session: 15, topic: 'Destroying & Distracting the defender.' },
    { session: 16, topic: 'Test 2', isTest: true },
    { session: 17, topic: 'Checkmate with one Rook.' },
    { session: 18, topic: 'Queen vs Bishop; Queen vs Knight.' },
    { session: 19, topic: 'Mixed Tactics.' },
    { session: 20, topic: 'Checkmate threat.' },
    { session: 21, topic: 'Passed Pawn & Pawn Promotion.' },
    { session: 22, topic: 'Trapping the Pieces.' },
    { session: 23, topic: 'Sacrificing the pieces to mate.' },
    { session: 24, topic: 'Test 3', isTest: true },
  ],

  'Foundation 2': [
    { session: 1,  topic: 'Revision of Foundation 1.' },
    { session: 2,  topic: 'Trapping the Pieces.' },
    { session: 3,  topic: 'Overloading.' },
    { session: 4,  topic: 'X-Ray Attack.' },
    { session: 5,  topic: 'Decoy / Deflection.' },
    { session: 6,  topic: 'Opening Traps.' },
    { session: 7,  topic: 'Intermediate moves.' },
    { session: 8,  topic: 'Test 1', isTest: true },
    { session: 9,  topic: 'Rule of the square.' },
    { session: 10, topic: 'Key Squares & Opposition.' },
    { session: 11, topic: 'King and Pawn vs King (4 scenarios).' },
    { session: 12, topic: 'Pawn Breakthroughs.' },
    { session: 13, topic: 'Windmill.' },
    { session: 14, topic: 'Forced Moves.' },
    { session: 15, topic: 'Smothered Mate.' },
    { session: 16, topic: 'Test 2', isTest: true },
    { session: 17, topic: "Checkmating Patterns – Legal's Mate & Epaulette Mate." },
    { session: 18, topic: 'Checkmating Patterns – Anastasia Mate & Arabian Mate.' },
    { session: 19, topic: "Checkmating Patterns – Boden's Mate & Dovetail Mate." },
    { session: 20, topic: 'Checkmating Patterns – Battery Mate & Hook Mate.' },
    { session: 21, topic: "Checkmating Patterns – Damiano's Mate & Lolli's Mate." },
    { session: 22, topic: "Checkmating Patterns – Greco's Mate & Pillsbury Mate." },
    { session: 23, topic: 'Checkmating Patterns – Blackburne Mate & Opera Mate.' },
    { session: 24, topic: 'Test 3', isTest: true },
  ],

  'Foundation 3': [
    { session: 1,  topic: 'Revision of Foundation 2.' },
    { session: 2,  topic: 'Checkmate in 3 (Easy).' },
    { session: 3,  topic: 'Introduction to World Champions.' },
    { session: 4,  topic: 'Attacking on h7 ideas.' },
    { session: 5,  topic: 'Mixed tactics (3 moves).' },
    { session: 6,  topic: 'Queen vs 7th rank pawn.' },
    { session: 7,  topic: 'Student Game review.' },
    { session: 8,  topic: 'Test 1', isTest: true },
    { session: 9,  topic: 'Checkmate in 3 (Difficult).' },
    { session: 10, topic: "Meet India's 1st World Champion & Short game." },
    { session: 11, topic: 'Attacking on g7 ideas.' },
    { session: 12, topic: 'Mixed tactics (3 moves).' },
    { session: 13, topic: 'Stalemate tactics.' },
    { session: 14, topic: 'King and Pawn vs King (Above the basic).' },
    { session: 15, topic: 'Student Game review.' },
    { session: 16, topic: 'Test 2', isTest: true },
    { session: 17, topic: "Meet India's youngest World Champion & his Short game." },
    { session: 18, topic: 'Attacking on f7 ideas.' },
    { session: 19, topic: 'Mixed tactics (3 moves).' },
    { session: 20, topic: 'Drawing tactics.' },
    { session: 21, topic: 'King and Pawn vs King (Above the basic).' },
    { session: 22, topic: 'Student Game review.' },
    { session: 23, topic: 'Checkmate in 4 (Easy).' },
    { session: 24, topic: 'Test 3', isTest: true },
  ],

  'Foundation 4': [
    { session: 1,  topic: 'Blunder Check Routine.' },
    { session: 2,  topic: 'Identifying Tactical Targets.' },
    { session: 3,  topic: 'Creating Threats (Active Thinking).' },
    { session: 4,  topic: 'Building a Simple Attack Plan.' },
    { session: 5,  topic: 'Identifying Weak Defenders.' },
    { session: 6,  topic: 'Spotting Tactical Triggers.' },
    { session: 7,  topic: 'Turning Small Advantages Into Tactics.' },
    { session: 8,  topic: 'Test 1', isTest: true },
    { session: 9,  topic: 'Compare Two Moves.' },
    { session: 10, topic: 'Eliminate Bad Moves First.' },
    { session: 11, topic: 'Capture or Not to Capture.' },
    { session: 12, topic: 'Improve Your Worst Piece.' },
    { session: 13, topic: 'King Safety Evaluation.' },
    { session: 14, topic: '2–3 Move Mini-Calculation.' },
    { session: 15, topic: 'Playing for Initiative.' },
    { session: 16, topic: 'Test 2', isTest: true },
    { session: 17, topic: 'King and Pawn race.' },
    { session: 18, topic: 'Cutting Off the King.' },
    { session: 19, topic: 'Lucena, Philidor.' },
    { session: 20, topic: 'Theoretically drawn endgames.' },
    { session: 21, topic: 'Slow play – Hypermodern chess.' },
    { session: 22, topic: 'Solidity.' },
    { session: 23, topic: 'Converting Material Advantage.' },
    { session: 24, topic: 'Test 3', isTest: true },
  ],

  'Intermediate 1': [
    { session: 1,  topic: 'How to calculate (intro).' },
    { session: 2,  topic: 'Centralisation of the King.' },
    { session: 3,  topic: 'Finding Candidate Moves (Checks, Captures, Threats).' },
    { session: 4,  topic: 'Principle of Two Weaknesses.' },
    { session: 5,  topic: 'Vishy Anand.' },
    { session: 6,  topic: 'Do Not Hurry.' },
    { session: 7,  topic: 'e4 e5 Italian structures.' },
    { session: 8,  topic: 'Monthly test', isTest: true },
    { session: 9,  topic: 'Blunder Check.' },
    { session: 10, topic: 'Passed Pawns.' },
    { session: 11, topic: 'Process of Elimination.' },
    { session: 12, topic: 'Schematic Thinking.' },
    { session: 13, topic: 'Karpov.' },
    { session: 14, topic: 'Transformation of Material Advantage.' },
    { session: 15, topic: 'e4-e5 Scotch structure.' },
    { session: 16, topic: 'Monthly test', isTest: true },
    { session: 17, topic: 'Forcing Moves.' },
    { session: 18, topic: 'Rook Activity.' },
    { session: 19, topic: 'Initiative.' },
    { session: 20, topic: 'Pawn Breaks.' },
    { session: 21, topic: 'Kasparov.' },
    { session: 22, topic: 'Good Knight vs Bad Bishop Part 1.' },
    { session: 23, topic: 'Exchange sacrifice (thematic).' },
    { session: 24, topic: 'Monthly test', isTest: true },
  ],

  'Intermediate 2': [
    { session: 1,  topic: 'Intuition.' },
    { session: 2,  topic: 'Good B vs Bad N Part 1.' },
    { session: 3,  topic: 'Basic endgame tactics.' },
    { session: 4,  topic: 'Double Bishop Part 1.' },
    { session: 5,  topic: 'Bobby Fischer.' },
    { session: 6,  topic: 'Multiple Minor Piece Endgames.' },
    { session: 7,  topic: 'e4 c6 Caro-Kann structures.' },
    { session: 8,  topic: 'Monthly test', isTest: true },
    { session: 9,  topic: 'King Safety.' },
    { session: 10, topic: 'Practical Rook Endgames Part 1.' },
    { session: 11, topic: 'Space Part 1.' },
    { session: 12, topic: 'Practical Rook Endgames Part 2.' },
    { session: 13, topic: 'Alexander Alekhine.' },
    { session: 14, topic: 'Capablanca.' },
    { session: 15, topic: 'e4 c5 Sicilian Boleslavsky structures.' },
    { session: 16, topic: 'Monthly test', isTest: true },
    { session: 17, topic: 'Piece Activity.' },
    { session: 18, topic: 'Practical Queen Endgames Part 1.' },
    { session: 19, topic: 'Material Advantage & Pawn Structure (intro).' },
    { session: 20, topic: 'Practical Queen Endgames Part 2.' },
    { session: 21, topic: 'Key Squares and Outposts.' },
    { session: 22, topic: 'Rubinstein.' },
    { session: 23, topic: 'Tactics.' },
    { session: 24, topic: 'Monthly test', isTest: true },
  ],

  'Intermediate 3': [
    { session: 1,  topic: 'Isolated, Doubled Pawns.' },
    { session: 2,  topic: 'Cut off, Back Rank Defence.' },
    { session: 3,  topic: 'Backward, Hanging Pawns.' },
    { session: 4,  topic: 'Lucena and Philidor.' },
    { session: 5,  topic: 'Mikhail Botvinnik.' },
    { session: 6,  topic: 'Ulf Andersson.' },
    { session: 7,  topic: "Prophylaxis: anticipating opponent's ideas." },
    { session: 8,  topic: 'Monthly test', isTest: true },
    { session: 9,  topic: 'Passer, Majority / Minority.' },
    { session: 10, topic: 'Short Side, Long Side.' },
    { session: 11, topic: 'Isolated Queen Pawn.' },
    { session: 12, topic: '3 vs 2, 4 vs 3.' },
    { session: 13, topic: 'Viktor Korchnoi.' },
    { session: 14, topic: 'Magnus Carlsen.' },
    { session: 15, topic: 'Transition from Middlegame to Endgame.' },
    { session: 16, topic: 'Monthly test', isTest: true },
    { session: 17, topic: 'Pawn Chains.' },
    { session: 18, topic: 'Pawn Endgames.' },
    { session: 19, topic: 'Sicilian Family.' },
    { session: 20, topic: 'Bishop + Knight Checkmate.' },
    { session: 21, topic: 'Slav / Caro-Kann / QGD Family.' },
    { session: 22, topic: 'Anatoly Karpov.' },
    { session: 23, topic: 'Handling Material Imbalances (R+P vs 2 minors etc.).' },
    { session: 24, topic: 'Monthly test', isTest: true },
  ],

  'Intermediate 4': [
    { session: 1,  topic: 'KID / Benoni Family.' },
    { session: 2,  topic: 'Same Bishop.' },
    { session: 3,  topic: 'Power of Two Bishops.' },
    { session: 4,  topic: 'Opposite Bishop.' },
    { session: 5,  topic: 'Opposite-Coloured Bishops.' },
    { session: 6,  topic: 'Vasily Smyslov.' },
    { session: 7,  topic: 'Weaknesses: creating and exploiting targets.' },
    { session: 8,  topic: 'Monthly test', isTest: true },
    { session: 9,  topic: 'Good Knight vs Bad Bishop.' },
    { session: 10, topic: 'Fortress draw.' },
    { session: 11, topic: 'Bad Piece Manoeuvring.' },
    { session: 12, topic: 'Winning Equal Endgames.' },
    { session: 13, topic: 'Attacking Uncastled King.' },
    { session: 14, topic: 'Pentala Harikrishna.' },
    { session: 15, topic: 'Fortress Concepts in Practice.' },
    { session: 16, topic: 'Monthly test', isTest: true },
    { session: 17, topic: 'Attacking the Castled King.' },
    { session: 18, topic: 'Queenless Middlegame.' },
    { session: 19, topic: 'Sacrifice.' },
    { session: 20, topic: 'Defending Worse Positions.' },
    { session: 21, topic: 'Counterplay.' },
    { session: 22, topic: 'Yuri Averbakh.' },
    { session: 23, topic: 'Defending Worse Positions: practical mindset & technique.' },
    { session: 24, topic: 'Monthly test', isTest: true },
  ],
}

// Map CC level names to syllabus keys
export function syllabusLevelFromCC(level: string): SyllabusLevel | null {
  const map: Record<string, SyllabusLevel> = {
    'Beginner':      'Beginner',
    'Foundation 1':  'Foundation 1',
    'Foundation 2':  'Foundation 2',
    'Foundation 3':  'Foundation 3',
    'Foundation 4':  'Foundation 4',
    'Intermediate':  'Intermediate 1',
    'Intermediate 1':'Intermediate 1',
    'Intermediate 2':'Intermediate 2',
    'Intermediate 3':'Intermediate 3',
    'Intermediate 4':'Intermediate 4',
  }
  return map[level] ?? null
}
